name: phpunit

on: [push]

jobs:
  phpunit:
    strategy:
      fail-fast: true
      matrix:
          php_version: ['8.0', '8.1', '8.2', '8.3']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}

      - name: PHPUnit Tests with coverage report
        if: ${{ matrix.php_version == '8.0' }}
        uses: php-actions/phpunit@v3
        with:
          version: 9.5
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          args: --coverage-text
          php_version: ${{ matrix.php_version }}
          php_extensions: pcov

      - name: PHPUnit Tests
        if: ${{ matrix.php_version != '7.3' }}
        uses: php-actions/phpunit@v3
        with:
          version: 9.5
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php_version }}
          php_extensions: pcov
